version: '3.9'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    command: ./wait-for-db.sh
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env


