"""Added new pwd column to user schema

Revision ID: 5a4111a1ce0d
Revises: c912764e2d9e
Create Date: 2025-08-15 02:25:56.037996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5a4111a1ce0d'
down_revision: Union[str, Sequence[str], None] = 'c912764e2d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_users_payment_source'), table_name='users')
    op.drop_column('users', 'payment_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('payment_source', mysql.VARCHAR(length=255), nullable=False))
    op.create_index(op.f('ix_users_payment_source'), 'users', ['payment_source'], unique=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
