from pydantic import BaseModel

class FoundReportCreate(BaseModel):
    founder_id: int
    item_id: int 
    description: str
    longitude: float
    latitude: float
    radius: float
    request_bounty: float
    #created_at: how do we handle this? should be auto generated by db
    